projects:
  foresite:
    schemaPath: graphql/schema.json
    includes:
      - graphql/**/*.graphql
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: swift
        generatedFileName: API.swift
        docsFilePath: graphql
        graphQLApiId: injogsdqr5durgkgs7df3q2okm
      endpoints:
        prod: >-
          https://fxxpwigoxrgs7nb3om45r4yw3u.appsync-api.us-west-2.amazonaws.com/graphql
